export type SosoKevitraStatusCode = 'BROUILLON' | 'EN_ATTENTE_VERIFICATION' | 'A_CORRIGER' | 'NON_PUBLIE' | 'EN_CONSULTATION' | 'A_L_ETUDE' | 'ACCEPTE' | 'REFUSE'
export type ContributionState = 'VISIBLE' | 'RETIRE' | 'MASQUE'
export interface SosoStatut { id: string; code: SosoKevitraStatusCode; ordre: number; libelle: string | null }
export interface SosoPerson { id: string; nom: string; prenom: string | null; nom_usage: string | null }
export interface SosoPhoto { id: string; chemin_photo: string; ordre: number; date_creation: string; url_photo?: string }
export interface SosoAction { id?: string; id_soso_kevitra?: string; description: string; ordre: number }
export interface SosoBudgetLine { id?: string; id_soso_kevitra?: string; designation: string; quantite: string; prix_unitaire_estime: string; ordre: number }
export interface SosoCategory { id: string; code: string; ordre: number; actif: boolean; libelle: string }
export interface SosoPublicItem { id: string; titre: string | null; description: string | null; objectif: string | null; beneficiaires: string | null; lieu: string | null; lieu_non_defini: boolean; periode_souhaitee: string | null; date_publication: string | null; date_fin_consultation: string | null; statut: SosoStatut; statut_fonctionnel: SosoKevitraStatusCode; consultation_ouverte: boolean; auteur: SosoPerson; photo_principale: SosoPhoto | null; nombre_soutiens: number; utilisateur_soutient: boolean }
export interface SosoContribution { id: string; categorie: SosoCategory; titre: string | null; description: string | null; etat: ContributionState; date_creation: string; date_modification: string; date_retrait: string | null; auteur: SosoPerson; photos: SosoPhoto[]; peut_modifier: boolean; peut_retirer: boolean; moderation_historique?: { action: 'MASQUER' | 'RESTAURER'; raison: string; date_action: string; personne_action: SosoPerson }[] }
export interface SosoTimelineEvent { action: string; commentaire: string | null; date_action: string; personne_action: SosoPerson }
export interface SosoProlongation { id: string; ancienne_date_fin_consultation: string; nouvelle_date_fin_consultation: string; raison: string; date_prolongation: string; personne_action: SosoPerson }
export interface SosoDecision { decision: 'ACCEPTE' | 'REFUSE'; observation: string | null; date_decision: string; personne_action: SosoPerson }
export interface SosoDetail extends Omit<SosoPublicItem, 'photo_principale'> { id_auteur: string; raison: string | null; details_realisation: string | null; ressources_necessaires: string | null; budget_non_defini: boolean; devise: string; date_creation: string; date_modification: string; actions: SosoAction[]; budget: SosoBudgetLine[]; total_budget_calcule: string; photos: SosoPhoto[]; soutiens: (SosoPerson & { date_soutien: string })[]; contributions: SosoContribution[]; verification_historique: SosoTimelineEvent[]; prolongations: SosoProlongation[]; decision_finale: SosoDecision | null }
export interface SosoDraftPayload { titre?: string; description?: string; raison?: string; objectif?: string; beneficiaires?: string; lieu?: string; lieu_non_defini?: boolean; details_realisation?: string; ressources_necessaires?: string; budget_non_defini?: boolean; devise?: string; periode_souhaitee?: string; actions?: SosoAction[]; budget?: SosoBudgetLine[] }
export interface SosoMyItem { id: string; titre: string | null; date_creation: string; date_modification: string; date_publication?: string | null; date_fin_consultation?: string | null; statut: SosoStatut }
