import { apiClient } from './apiClient'
import type { ApiSuccess } from '../types/api'
import type { TranslationKey } from '../i18n/types'
export type StatutJournee='BROUILLON'|'OUVERTE'|'CLOTUREE'; export type TypeDonateur='TARANAKA'|'SAMPANA'|'FOYER'|'PERSONNE'; export type TypeDon='ARGENT'|'MATERIEL'
export type Ref={id:string;nom?:string;prenom?:string|null}; export interface Journee{id:string;date_journee:string;statut:StatutJournee;observation:string|null;taranaka:Ref[]}
export interface Don{id:string;journee:{id:string;date_journee:string};type_donateur:TypeDonateur;donateur:Ref&{type_foyer?:string};type_don:TypeDon;montant:string|null;devise:string|null;designation:string|null;quantite:string|null;unite:string|null;observation:string|null;statut:'VALIDE'|'ANNULE';date_creation:string;motif_annulation:string|null;warnings?:{code:string;message:string}[]}
export interface DonPayload{type_donateur:TypeDonateur;id_donateur:string;type_don:TypeDon;montant?:string;devise?:string;designation?:string;quantite?:string;unite?:string;observation?:string|null}
export interface FoyerPersistant{id:string;type_foyer:string;statut:string;personne_1:Ref;personne_2:Ref|null}
const base='/api/journees-alahadin-taranaka';
export const getJournees=()=>apiClient<ApiSuccess<Journee[]>>(base); export const getJournee=(id:string)=>apiClient<ApiSuccess<Journee>>(`${base}/${id}`); export const createJournee=(p:{date_journee:string;observation?:string|null;id_taranaka:string[]})=>apiClient<ApiSuccess<Journee>>(base,{method:'POST',body:p}); export const updateJournee=(id:string,p:{date_journee:string;observation?:string|null;id_taranaka:string[]})=>apiClient<ApiSuccess<Journee>>(`${base}/${id}`,{method:'PUT',body:p});
export const ouvrirJournee=(id:string)=>apiClient<ApiSuccess<Journee>>(`${base}/${id}/ouvrir`,{method:'POST',body:{}}); export const cloturerJournee=(id:string)=>apiClient<ApiSuccess<Journee>>(`${base}/${id}/cloturer`,{method:'POST',body:{}}); export const rouvrirJournee=(id:string)=>apiClient<ApiSuccess<Journee>>(`${base}/${id}/rouvrir`,{method:'POST',body:{}});
export const getDons=(id:string)=>apiClient<ApiSuccess<Don[]>>(`${base}/${id}/dons`); export const createDon=(id:string,p:DonPayload)=>apiClient<ApiSuccess<Don>>(`${base}/${id}/dons`,{method:'POST',body:p}); export const updateDon=(j:string,id:string,p:DonPayload)=>apiClient<ApiSuccess<Don>>(`${base}/${j}/dons/${id}`,{method:'PUT',body:p}); export const annulerDon=(j:string,id:string,motif_annulation:string)=>apiClient<ApiSuccess<Don>>(`${base}/${j}/dons/${id}/annuler`,{method:'POST',body:{motif_annulation}}); export const getStatistiques=(id:string)=>apiClient<ApiSuccess<any>>(`${base}/${id}/statistiques`); export const getFoyerPersistant=(id:string)=>apiClient<ApiSuccess<FoyerPersistant|null>>(`/api/personnes/${id}/foyer-persistant`)
const errorKeys: Record<string, TranslationKey> = {
  JOURNEE_INVALID: 'alahadin.errors.JOURNEE_INVALID', JOURNEE_TARANAKA_REQUIRED: 'alahadin.errors.JOURNEE_TARANAKA_REQUIRED', JOURNEE_TARANAKA_DUPLICATE: 'alahadin.errors.JOURNEE_TARANAKA_DUPLICATE', JOURNEE_TARANAKA_INVALID: 'alahadin.errors.JOURNEE_TARANAKA_INVALID', JOURNEE_TARANAKA_NOT_FOUND: 'alahadin.errors.JOURNEE_TARANAKA_NOT_FOUND', JOURNEE_NOT_FOUND: 'alahadin.errors.JOURNEE_NOT_FOUND', JOURNEE_STATE_INVALID: 'alahadin.errors.JOURNEE_STATE_INVALID', JOURNEE_TRANSITION_INVALID: 'alahadin.errors.JOURNEE_TRANSITION_INVALID', DON_INVALID: 'alahadin.errors.DON_INVALID', DON_DONATEUR_INVALID: 'alahadin.errors.DON_DONATEUR_INVALID', DON_ARGENT_INVALID: 'alahadin.errors.DON_ARGENT_INVALID', DON_MATERIEL_INVALID: 'alahadin.errors.DON_MATERIEL_INVALID', DON_RATTACHEMENT_INVALID: 'alahadin.errors.DON_RATTACHEMENT_INVALID', DON_CANCELLATION_REASON_REQUIRED: 'alahadin.errors.DON_CANCELLATION_REASON_REQUIRED', DON_JOURNEE_NOT_FOUND: 'alahadin.errors.DON_JOURNEE_NOT_FOUND', DON_NOT_FOUND: 'alahadin.errors.DON_NOT_FOUND', DON_ELEMENT_NOT_FOUND: 'alahadin.errors.DON_ELEMENT_NOT_FOUND', DON_PERSONNE_NOT_FOUND: 'alahadin.errors.DON_PERSONNE_NOT_FOUND', DON_FOYER_NOT_FOUND: 'alahadin.errors.DON_FOYER_NOT_FOUND', DON_JOURNEE_NOT_OPEN: 'alahadin.errors.DON_JOURNEE_NOT_OPEN', DON_ALREADY_CANCELLED: 'alahadin.errors.DON_ALREADY_CANCELLED', DON_TARANAKA_NOT_ALLOWED: 'alahadin.errors.DON_TARANAKA_NOT_ALLOWED'
}
export const alahadinErrorKey = (code?: string): TranslationKey | undefined => code ? errorKeys[code] : undefined
export const journeeStatusKey = (code: StatutJournee): TranslationKey => ({ BROUILLON: 'alahadin.statusDraft', OUVERTE: 'alahadin.statusOpen', CLOTUREE: 'alahadin.statusClosed' } as const)[code]
export const donStatusKey = (code: Don['statut']): TranslationKey => ({ VALIDE: 'alahadin.statusValid', ANNULE: 'alahadin.statusCancelled' } as const)[code]
export const donTypeKey = (code: TypeDon): TranslationKey => ({ ARGENT: 'alahadin.money', MATERIEL: 'alahadin.material' } as const)[code]
export const donorTypeKey = (code: TypeDonateur): TranslationKey => ({ TARANAKA: 'alahadin.donorTaranaka', SAMPANA: 'alahadin.donorSampana', FOYER: 'alahadin.donorFoyer', PERSONNE: 'alahadin.donorPerson' } as const)[code]
export const foyerTypeKey = (code?: string): TranslationKey => code === 'MONOPARENTAL' ? 'alahadin.foyerMonoparental' : 'alahadin.foyerCouple'