import { useEffect, useMemo, useState } from 'react'
import { CirclePlus, Pencil, Send, Trash2 } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { deleteDraft, getMyDrafts, getMySoso, submitSoso } from '../../api/sosoKevitra'
import { ApiError } from '../../api/apiClient'
import { SosoCard, SosoPageHeading, StatusBadge } from '../../components/sosoKevitra/SosoKevitraShared'
import { useLanguage } from '../../hooks/useLanguage'
import { useLatestRequest } from '../../hooks/useLatestRequest'
import type { SosoMyItem } from '../../types/sosoKevitra'
import './SosoKevitra.css'

export function MesSosoKevitraPage() {
  const { language, t } = useLanguage(); const navigate = useNavigate(); const [items, setItems] = useState<SosoMyItem[]>([]); const [tab, setTab] = useState<'ALL' | 'DRAFTS'>('ALL'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState<string | null>(null); const { startRequest, isCurrentRequest } = useLatestRequest()
  const load = async () => { const r = startRequest(); if (isCurrentRequest(r)) { setLoading(true); setError('') } try { const [all, drafts] = await Promise.all([getMySoso(language), getMyDrafts(language)]); if (isCurrentRequest(r)) { const map = new Map<string, SosoMyItem>(); [...(all.data ?? []), ...(drafts.data ?? [])].forEach(item => map.set(item.id, item)); setItems([...map.values()].sort((a, b) => b.date_modification.localeCompare(a.date_modification))) } } catch (e) { if (isCurrentRequest(r)) setError(e instanceof ApiError ? e.message : t('soso.loadError')) } finally { if (isCurrentRequest(r)) setLoading(false) } }
  useEffect(() => { void load() }, [language])
  const act = async (item: SosoMyItem, kind: 'submit' | 'delete') => { if (kind === 'delete' && !window.confirm(t('soso.deleteConfirm'))) return; setBusy(item.id); try { if (kind === 'submit') await submitSoso(item.id, language); else await deleteDraft(item.id); await load() } catch (e) { setError(e instanceof ApiError ? e.message : t('soso.actionError')) } finally { setBusy(null) } }
  const stats = useMemo(() => ({ total: items.length, published: items.filter(x => x.statut.code === 'EN_CONSULTATION').length, studying: items.filter(x => x.statut.code === 'A_L_ETUDE').length, pending: items.filter(x => x.statut.code === 'EN_ATTENTE_VERIFICATION').length, drafts: items.filter(x => ['BROUILLON', 'A_CORRIGER'].includes(x.statut.code)).length }), [items])
  const shown = tab === 'DRAFTS' ? items.filter(x => ['BROUILLON', 'A_CORRIGER'].includes(x.statut.code)) : items
  return <section className="soso-page"><SosoPageHeading title={t('soso.myTitle')} subtitle={t('soso.mySubtitle')}><Link className="primary soso-new" to="/soso-kevitra/nouveau"><CirclePlus size={18}/>{t('soso.new')}</Link></SosoPageHeading><div className="soso-tabs"><Link to="/soso-kevitra">{t('soso.all')}</Link><button className={tab === 'ALL' ? 'active' : ''} onClick={() => setTab('ALL')}>{language === 'fr' ? 'Toutes mes suggestions' : 'Ny soso-kevitro rehetra'}</button><button className={tab === 'DRAFTS' ? 'active' : ''} onClick={() => setTab('DRAFTS')}>{language === 'fr' ? 'Brouillons' : 'Volavola'}</button></div>{!loading && <div className="soso-stat-grid"><div><strong>{stats.total}</strong><span>{language === 'fr' ? 'Total' : 'Fitambarany'}</span></div><div className="published"><strong>{stats.published}</strong><span>{language === 'fr' ? 'Publiées' : 'Navoaka'}</span></div><div className="studying"><strong>{stats.studying}</strong><span>{language === 'fr' ? 'En étude' : 'Eo am-pandinihana'}</span></div><div className="pending"><strong>{stats.pending}</strong><span>{language === 'fr' ? 'En attente' : 'Miandry'}</span></div><div className="draft"><strong>{stats.drafts}</strong><span>{language === 'fr' ? 'Brouillons' : 'Volavola'}</span></div></div>}{error && <p className="form-error">{error}</p>}{loading ? <p className="auth-loading">{t('soso.loading')}</p> : !shown.length ? <section className="soso-empty"><h2>{tab === 'DRAFTS' ? (language === 'fr' ? 'Aucun brouillon' : 'Tsy misy volavola') : t('soso.noMine')}</h2><Link className="primary" to="/soso-kevitra/nouveau"><CirclePlus size={17}/>{t('soso.new')}</Link></section> : <div className="soso-my-list">{shown.map(item => { const editable = ['BROUILLON', 'A_CORRIGER'].includes(item.statut.code); const deletable = item.statut.code === 'BROUILLON'; return <article key={item.id} className="soso-my-row"><SosoCard item={item} language={language} summary/><StatusBadge status={item.statut}/><div className="soso-row-actions"><Link to={`/soso-kevitra/${item.id}`}>{t('soso.open')}</Link>{editable && <button disabled={busy === item.id} onClick={() => navigate(`/soso-kevitra/${item.id}/modifier`)}><Pencil size={15}/>{t('soso.edit')}</button>}{editable && <button disabled={busy === item.id} onClick={() => void act(item, 'submit')}><Send size={15}/>{item.statut.code === 'A_CORRIGER' ? t('soso.resubmit') : t('soso.submit')}</button>}{deletable && <button className="danger" disabled={busy === item.id} onClick={() => void act(item, 'delete')}><Trash2 size={15}/>{t('soso.delete')}</button>}</div></article> })}</div>}</section>
}