import { useEffect, useState } from 'react'
import { Send, Trash2, UploadCloud, X } from 'lucide-react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import { createDraft, deleteDraft, deleteSosoPhoto, getSosoDetail, reorderSosoPhotos, submitSoso, updateDraft, uploadSosoPhotos } from '../../api/sosoKevitra'
import { ApiError } from '../../api/apiClient'
import { SosoKevitraForm } from '../../components/sosoKevitra/SosoKevitraForm'
import { SosoPageHeading } from '../../components/sosoKevitra/SosoKevitraShared'
import { useLanguage } from '../../hooks/useLanguage'
import type { SosoDetail, SosoDraftPayload } from '../../types/sosoKevitra'
import './SosoKevitra.css'

export function SosoKevitraFormPage() {
  const { id } = useParams(); const { search } = useLocation(); const edit = Boolean(id); const { language, t } = useLanguage(); const navigate = useNavigate(); const [detail, setDetail] = useState<SosoDetail | null>(null); const [loading, setLoading] = useState(edit); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [files, setFiles] = useState<File[]>([])
  useEffect(() => { if (new URLSearchParams(search).get('photos') === 'error') setError(language === 'fr' ? 'Le brouillon a été créé, mais certaines photos n’ont pas pu être envoyées. Vous pouvez réessayer.' : 'Voatahiry ny volavola, saingy tsy tafiditra ny sary sasany. Azonao andramana indray.'); if (!id) return; void (async () => { try { const result = await getSosoDetail(id, language); setDetail(result.data ?? null) } catch (caught) { setError(caught instanceof ApiError ? caught.message : t('soso.loadError')) } finally { setLoading(false) } })() }, [id, language])
  const addFiles = (selected: FileList | null) => setFiles(current => [...current, ...Array.from(selected ?? [])].slice(0, Math.max(0, 10 - (detail?.photos.length ?? 0))))
  const moveExisting = async (from: number, to: number) => { if (!id || !detail || to < 0 || to >= detail.photos.length) return; const ids = detail.photos.map(photo => photo.id); [ids[from], ids[to]] = [ids[to], ids[from]]; setSaving(true); try { await reorderSosoPhotos(id, ids); const result = await getSosoDetail(id, language); setDetail(result.data ?? null) } catch (caught) { setError(caught instanceof ApiError ? caught.message : t('soso.actionError')) } finally { setSaving(false) } }
  const removeExisting = async (photoId: string) => { if (!id || !window.confirm(t('soso.deleteConfirm'))) return; setSaving(true); try { await deleteSosoPhoto(id, photoId); setDetail(current => current ? { ...current, photos: current.photos.filter(photo => photo.id !== photoId) } : current) } catch (caught) { setError(caught instanceof ApiError ? caught.message : t('soso.actionError')) } finally { setSaving(false) } }
  const save = async (payload: SosoDraftPayload) => { setSaving(true); setError(''); try { const result = edit && id ? await updateDraft(id, payload, language) : await createDraft(payload, language); const saved = result.data; if (!saved) throw new Error(t('soso.actionError')); if (files.length) await uploadSosoPhotos(saved.id, files); navigate(`/soso-kevitra/${saved.id}`) } catch (caught) { setError(caught instanceof ApiError ? caught.message : caught instanceof Error ? caught.message : t('soso.actionError')) } finally { setSaving(false) } }
  const submit = async () => { if (!id) return; setSaving(true); try { await submitSoso(id, language); navigate(`/soso-kevitra/${id}`) } catch (caught) { setError(caught instanceof ApiError ? caught.message : t('soso.actionError')) } finally { setSaving(false) } }
  const remove = async () => { if (!id || !window.confirm(t('soso.deleteConfirm'))) return; setSaving(true); try { await deleteDraft(id); navigate('/soso-kevitra/mes') } catch (caught) { setError(caught instanceof ApiError ? caught.message : t('soso.actionError')) } finally { setSaving(false) } }
  if (loading) return <p className="auth-loading">{t('soso.loading')}</p>
  if (edit && !detail) return <p className="form-error">{error || t('soso.notFound')}</p>
  const allowed = !edit || ['BROUILLON', 'A_CORRIGER'].includes(detail?.statut.code ?? '')
  const photoSection = <section className="soso-form-section soso-photo-section"><h2><span>4</span>{t('soso.photos')} <small>({language === 'fr' ? 'optionnel' : 'tsy voatery'})</small></h2><label className="soso-photo-drop"><UploadCloud size={30}/><strong>{language === 'fr' ? 'Cliquer pour ajouter des photos' : 'Tsindrio raha hanampy sary'}</strong><small>JPEG, PNG, WebP · {language === 'fr' ? '10 photos maximum' : 'Sary 10 farafahabetsany'}</small><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={event => addFiles(event.target.files)} /></label>{files.length > 0 && <div className="soso-photo-previews">{files.map((file, index) => <figure key={`${file.name}-${index}`}><img src={URL.createObjectURL(file)} alt={file.name}/><button type="button" aria-label={t('soso.remove')} onClick={() => setFiles(current => current.filter((_, itemIndex) => itemIndex !== index))}><X size={15}/></button></figure>)}</div>}{detail?.photos?.length ? <div className="soso-photo-previews existing">{detail.photos.map((photo, index) => <figure key={photo.id}><img src={photo.url_photo} alt=""/><figcaption><button type="button" disabled={saving || index === 0} onClick={() => void moveExisting(index, index - 1)} aria-label="Monter">↑</button><button type="button" disabled={saving || index === detail.photos.length - 1} onClick={() => void moveExisting(index, index + 1)} aria-label="Descendre">↓</button><button type="button" disabled={saving} aria-label={t('soso.delete')} onClick={() => void removeExisting(photo.id)}><Trash2 size={14}/></button></figcaption></figure>)}</div> : null}</section>
  return <section className="soso-page soso-form-page"><Link className="soso-back" to={edit ? `/soso-kevitra/${id}` : '/soso-kevitra/mes'}>← {t('soso.back')}</Link><SosoPageHeading title={edit ? t('soso.editTitle') : t('soso.createTitle')} subtitle={t('soso.formSubtitle')}/>{error && <p className="form-error" role="alert">{error}</p>}{!allowed ? <section className="soso-empty">{t('soso.editUnavailable')}</section> : <><SosoKevitraForm initial={detail ?? undefined} saving={saving} onSave={save} onCancel={() => navigate(edit ? `/soso-kevitra/${id}` : '/soso-kevitra/mes')} photos={photoSection} submitLabel={edit ? t('soso.save') : t('soso.createDraft')} labels={{ main: language === 'fr' ? 'Informations principales' : 'Fampahalalana fototra', why: language === 'fr' ? 'Pourquoi cette suggestion ?' : 'Antony anolorana ity hevitra ity', implementation: language === 'fr' ? 'Mise en œuvre' : 'Fanatanterahana', title: t('soso.fieldTitle'), period: t('soso.period'), description: t('soso.description'), reason: t('soso.reason'), objective: t('soso.objective'), beneficiaries: t('soso.beneficiaries'), location: t('soso.location'), locationUnknown: t('soso.locationUnknown'), realisation: t('soso.realisation'), resources: t('soso.resources'), actions: t('soso.actions'), addAction: language === 'fr' ? 'Ajouter une action' : 'Manampy asa', remove: t('soso.remove'), actionPlaceholder: t('soso.actionPlaceholder'), budget: t('soso.budget'), addBudget: language === 'fr' ? 'Ajouter une ligne' : 'Manampy andalana', budgetUnknown: t('soso.budgetUnknown'), total: t('soso.total'), designation: t('soso.designation'), quantity: t('soso.quantity'), price: t('soso.price'), saving: t('soso.saving'), cancel: t('soso.cancel') }}/>{edit && <div className="soso-after-form-actions"><button disabled={saving} onClick={() => void submit()}><Send size={16}/>{detail?.statut.code === 'A_CORRIGER' ? t('soso.resubmit') : t('soso.submit')}</button>{detail?.statut.code === 'BROUILLON' && <button className="danger" disabled={saving} onClick={() => void remove()}><Trash2 size={16}/>{t('soso.delete')}</button>}</div>}</>}</section>
}